name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup ssh key
      run: |
        ssh-keygen -t ed25519 -N '' -f ~/.ssh/id_ed25519
        cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
        chmod 700 ~/
        chmod 400 ~/.ssh/authorized_keys
    - name: Check ssh access
      run: |
        ssh -o StrictHostKeyChecking=no localhost uptime
    - name: Setup systemd
      run: |
        loginctl enable-linger $USER
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Run tests
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version)
        rvm in . do gem install bundler
        rvm in . do bundle install --with development
        rvm in . do bundle exec rake test
